### ISSUE TITLE
Resource are not being deleted after uninstalling the pipeline-operator 

### ISSUE THREAD

**Issue by sudhirverma** [openshift/tektoncd-pipeline-operator#176] opened 2020-01-07 14:50 UTC
When I uninstall the pipeline-operator from the OperatorHub it doesn't delete all the resources.

```
oc get crd

output after uninstalling the pipeline-operator.
pipelineresources.tekton.dev                                2020-01-07T07:57:19Z
pipelineruns.tekton.dev                                     2020-01-07T07:57:18Z
pipelines.tekton.dev                                        2020-01-07T07:57:18Z
```

after uninstalling the pipeline-operator from OperatorHub it should delete all the tekton resources.

issue: https://github.com/redhat-developer/vscode-tekton/issues/1

**Comment by vdemeester** [comment] 2020-01-07 14:56
/cc @sthaha @nikhil-thomas 
I think this is by design (initially)

**Comment by sthaha** [comment] 2020-01-08 00:15
@sudhirverma  To the best of my knowledge this is the expected behaviour of Operator Lifecycle Manager. I do agree it sounds counter intuitive.  The  recommended way to uninstall the operator is to remove the cluster-wide CR (custom-resource) called `cluster`  which the operator creates automatically when it is subscribed to e.g.

```
oc delete config.operator.tekton.dev cluster
```

This is explained in the blog series that @nikhil-thomas wrote some time back - https://medium.com/@nikhilthomas1/right-way-to-uninstall-openshift-pipelines-fromopenshift-4-x-fb2a7b7c492c 

I think we must add that section to the [tutorial](https://github.com/openshift/pipelines-tutorial#install-openshift-pipelines) as well.

For now, I am closing this as not a bug until OLM gives us an option. 

@vdemeester thanks for the ping 🙏 👼

**Closed by sthaha** 2020-01-08 00:15 UTC
